remote_theme: just-the-docs/just-the-docs
title: Task Management System
description: Documentation for the task management system used for coaching multiple companies
markdown: kramdown
color_scheme: light

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/jl-volta/disco_v3_docs" 